# NON-CANONICAL requirements list 
# Really just used for setting up conda env 

name: sun-noe-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - gunicorn 
  - flask 
  - gspread
  - oauth2client
  - pandas
  - pipfile
  - pytest
  - pip:
    - twilio

